#!/bin/bash



set -x

#list all the S3 buckets


aws s3 ls

echo "print list of s3 buckets"


#list all the ec2 instances

aws ec2 describe-instances

echo "print the list of ec2 instances"


#list all the lambda functions

aws lambda list-functions


echo "print all the list of lambda functions"


#list iam users

aws iam list-users

echo "print all the list of iam users"

